### PR TITLE
add: hexagonal, adapter and onion architecture

### PR DESCRIPTION
**Pull request by AndrusGerman**
Add different layers of attractions, to simplify app growth and make it easier to use different stores.

```go
	var memoryStore = keyvaluestorememory.NewKeyValueMemoryStore()
	var keyvaluestore = keyvaluestore.NewKeyValueStore(memoryStore)
```

Thanks to adapter we can add different stores, for example to handle elements in memory or on hard disk.
Internal adapters live in `internal\adapter\keyvaluestore`  where we would currently have `keyvaluestorememory`

The app would also feature 'handler' adapters, these allow implementation for GRPC calls or in this case HTTP
`internal\adapter\handler\http`

A port package that allows you to connect different pieces of the application
`internal\core\port` and to be able to have a more global abstraction.

### CODE REVIEW

**Comment by AndrusGerman** [comment]
This also seems to partially solve one of the problems discussed in [issue 27](https://github.com/defoeam/kvs/issues/27).

**Comment by defoeam** [comment]
Hey Andrus, PR looks good so far, ill finish my review later. I have to ask how you stumbled across this repo? We are working on this project for a club, and just want to know where you're coming from. If you could reply here that would be great

**Comment by AndrusGerman** [comment]
@defoeam Sure, I'm waiting for your review. As for how I found the project, it was with one of the issue tags. PS: I'm from Venezuela. 🫣

**Comment by defoeam** [comment]
@AndrusGerman One of the issue tags? Can you elaborate some more? P.S. I'm from Minnesota, U.S.A.

**Comment by AndrusGerman** [comment]
@defoeam [goodfirstissues.com](https://goodfirstissues.com/)
I was checking this page to see if I could do some collaboration and this project just came up. 🙂‍↕️

**Review by louislef299 — COMMENTED** [review]
Sorry this isn't really what we are looking for. Thanks anyways!

**Pull request closed without merging**
